import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/Navbar";
import {Footer} from "@/components/Footer";

const manrope = Manrope({
    subsets: ["latin"],
    variable: "--font-manrope",
});

export const metadata: Metadata = {
    title: "Spezi",
    description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en" className={manrope.variable}>
            <body className="font-sans antialiased">
                <Navbar />
                    <main className="px-8 md:px-32 lg:px-[200px]">
                        {children}
                        <Footer />
                    </main>
            </body>
        </html>
    );
}


